language: node_js
script:
  - cd api && nvm i node && node -v && npm i jest && npm i supertest && npm i mock-mongoose && npm test
  - cd .. && cd client && nvm i node && node -v && npm i jest && npm i supertest && npm test